RANDOM_SEED = 42

MISSINGNESS_LEVELS = [0.10, 0.20, 0.30, 0.50]
MISSINGNESS_MECHANISMS = ["MCAR", "MAR", "MNAR"]
BOOTSTRAP_ITERATIONS = 30
SAMPLE_SIZE = 5000

DATASETS = ["asia", "sachs"]

RESULTS_DIR = "results"
DATA_DIR = "data"
